config/routes.rb
WednesdayShelf::Application.routes.draw do
  devise_for :users
  resources :users do
    resources :pull_lists, only: [:show]
    resources :pulls, only: [:create, :destroy]
    member do
      get :settings
    end
  end

   root 'home#index'
   resources :releases
   resources :issues, only: [:show] do
      get :add_to_list
      get :remove_from_list
   end
end

app/views/shared/_comic.html.haml
%li.comic(id="#{issue.diamond_number}" data-name="#{issue.clean_title}" data-pull-id="#{issue.pull_id}")
  .card-flip-container
    .front
      =image_tag(issue.hero_cover.grid_cover.url, class: "comic-issue-cover")
    .back
      .title= issue.clean_title
      .lower-buttons
        %a.card-link.js-card-link{data: {id: issue.id}}
        =link_to 'More Info', issue_path(issue.id),class: ' card-link'

app/views/shared/_comic_list.html.haml
%ul#your-pulls.comic-list
  %h2.list-header
  - release.subscribed_issues.each do |issue|
    = render partial: 'shared/comic', locals: {user: user, issue: issue}

%ul#released-comics.comic-list
  %h2.list-header
  - release.unsubscribed_issues.each do |issue|
    = render partial: 'shared/comic', locals: {user: user, issue: issue}


:javascript
  $(function(){
    new WednesdayShelf.AddOrRemoveToPullList("ul#your-pulls", "ul#released-comics", #{current_user.present? ? current_user.id : false});
  });

app/views/shared/_comic_nav.html.haml
#comic_release_nav
  .previous{style: navigation_helper(data.previous)}
    =link_to release_path(data.previous), class: "lateral-navigation-button", id: "nav-left" do
      = fa_icon "chevron-left"
      %span
        Last Week

  .date= data.pretty_date
  .next{style: navigation_helper(data.next)}
    =link_to release_path(data.next), class: "lateral-navigation-button", id: "nav-right" do
      %span
        Next Week
      =fa_icon "chevron-right"

app/views/shared/_header.html.haml
#nav-header
  .interface_pane
    = image_tag('ws_logo.png')
  .info_pane
    %ul.nav
      %li.nav-item.sign-up
        Sign Up
      %li.nav-item.sign-in
        Sign In
      %li.nav-item
        About
      %li.nav-item
        Blog

app/views/shared/_top_bar.html.haml
.fixed
  %nav.top-bar(data-topbar)
    %ul.title-area
    %section.top-bar-section
      %ul.right
        - if current_user.present?
          %li
            %a My WS
          %li
            =link_to "Sign Out", destroy_user_session_path
        -else
          %li
            =link_to "Log in", new_user_session_path
          %li
            =link_to "Sign In", new_user_registration_path
      %ul.left
        %li
          =link_to "WednesdayShelf", root_path, class: 'top-bar-h1'